export type Locale = "en" | "fa";

export function localePath(path: string, locale: Locale): string {
  const normalized = path.startsWith("/") ? path : `/${path}`;
  return locale === "fa" ? `/fa${normalized === "/" ? "" : normalized}` : normalized;
}

export const copy = {
  en: {
    language: "فارسی", explore: "Explore", designSystem: "Design system", creators: "For creators", signIn: "Sign in", startSelling: "Start selling", close: "Close menu", open: "Open menu", primary: "Primary", mobile: "Mobile", announcement: "New: verified MCP servers with transparent permission reviews", marketplace: "The marketplace for AI building blocks", heroStop: "Stop prompting", heroScratch: "from scratch.", heroStart: "Start from what works.", heroIntro: "Prompts, skills, agents and MCP servers built by people who already got the model to behave — each one listed with its permissions, compatibility and safety review in plain sight.", exploreMarketplace: "Explore the marketplace", sellWork: "Sell your work", declared: "Every listing declares what it touches before you install it.", worksWith: "Works with", featuredEyebrow: "Chosen with care", featuredTitle: "Featured building blocks", viewAll: "View all {count} listings", unavailable: "Marketplace data is temporarily unavailable. Please try again shortly.", trustEyebrow: "Trust is product information.", collectionsEyebrow: "Curated collections", practiceEyebrow: "Browse by practice", creatorsEyebrow: "People worth following", featuredCreators: "Featured creators", inboxEyebrow: "A quieter, better inbox", inboxTitle: "One useful release every Friday.", account: "Your account", signedInAs: "Signed in as", signOut: "Sign out", accountIntro: "Use one account for the TermSpace marketplace and editorial library.", createAccount: "Create account", needAccount: "Need an account? Register", registered: "Already registered? Sign in", email: "Email", password: "Password", wait: "Please wait…", serviceError: "Account services are temporarily unavailable.", home: "Home", footer: "The marketplace for AI building blocks. Carefully made, clearly explained." },
  fa: {
    language: "English", explore: "کاوش", designSystem: "سیستم طراحی", creators: "برای سازندگان", signIn: "ورود", startSelling: "شروع فروش", close: "بستن منو", open: "باز کردن منو", primary: "اصلی", mobile: "موبایل", announcement: "تازه: سرورهای MCP تأییدشده با بررسی شفاف مجوزها", marketplace: "بازارچهٔ اجزای سازندهٔ هوش مصنوعی", heroStop: "از درخواست‌های تکراری", heroScratch: "از صفر دست بکشید.", heroStart: "از چیزی که کار می‌کند شروع کنید.", heroIntro: "پرامپت‌ها، مهارت‌ها، عامل‌ها و سرورهای MCP را افرادی ساخته‌اند که مدل را به کار گرفته‌اند؛ هر مورد با مجوزها، سازگاری و بررسی ایمنی شفاف معرفی می‌شود.", exploreMarketplace: "کاوش در بازارچه", sellWork: "فروش کار شما", declared: "هر فهرست پیش از نصب مشخص می‌کند با چه چیزهایی تعامل دارد.", worksWith: "سازگار با", featuredEyebrow: "با دقت انتخاب‌شده", featuredTitle: "اجزای منتخب", viewAll: "مشاهدهٔ {count} فهرست", unavailable: "داده‌های بازارچه موقتاً در دسترس نیست. لطفاً کمی بعد دوباره تلاش کنید.", trustEyebrow: "اعتماد، بخشی از اطلاعات محصول است.", collectionsEyebrow: "مجموعه‌های گزینش‌شده", practiceEyebrow: "بر اساس شیوهٔ کار کاوش کنید", creatorsEyebrow: "افرادی که ارزش دنبال‌کردن دارند", featuredCreators: "سازندگان منتخب", inboxEyebrow: "صندوق ورودی آرام‌تر و مفیدتر", inboxTitle: "هر جمعه یک انتشار مفید.", account: "حساب شما", signedInAs: "واردشده با", signOut: "خروج", accountIntro: "با یک حساب به بازارچهٔ ترم‌اسپیس و کتابخانهٔ تحریریه دسترسی داشته باشید.", createAccount: "ساخت حساب", needAccount: "حساب ندارید؟ ثبت‌نام کنید", registered: "قبلاً ثبت‌نام کرده‌اید؟ وارد شوید", email: "ایمیل", password: "رمز عبور", wait: "لطفاً صبر کنید…", serviceError: "خدمات حساب موقتاً در دسترس نیست.", home: "خانه", footer: "بازارچهٔ اجزای هوش مصنوعی؛ با دقت ساخته‌شده و شفاف توضیح‌داده‌شده." },
} as const;

